"use client";

import React, { useCallback, useEffect, useId, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { useDismissableOverlay } from "@/lib/use-dismissable-overlay";

interface PagefindResultData {
  url: string;
  meta: { title?: string };
  excerpt: string;
}

interface PagefindResult {
  id: string;
  data: () => Promise<PagefindResultData>;
}

interface PagefindModule {
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
  init?: () => Promise<void>;
}

let pagefindPromise: Promise<PagefindModule | null> | null = null;

function loadPagefind(): Promise<PagefindModule | null> {
  if (pagefindPromise) return pagefindPromise;
  // Generated by Pagefind into the static export at build time (postbuild script);
  // it doesn't exist as a module at compile time, so it can't be statically resolved.
  const importPagefind = new Function("path", "return import(/* webpackIgnore: true */ path)") as (
    path: string,
  ) => Promise<PagefindModule>;
  pagefindPromise = importPagefind("/pagefind/pagefind.js")
    .then(async (mod) => {
      await mod.init?.();
      return mod;
    })
    .catch(() => null);
  return pagefindPromise;
}

interface ResolvedResult {
  id: string;
  url: string;
  title: string;
  excerpt: string;
}

/** Static, client-side search over the built docs — indexed at build time by Pagefind. No backend. */
export default function SearchDialog() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<ResolvedResult[]>([]);
  const [activeIdx, setActiveIdx] = useState(0);
  const [unavailable, setUnavailable] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const listboxId = useId();

  // Global ⌘K/Ctrl+K toggle only; Escape-to-close, Tab trapping and scroll lock live in
  // useDismissableOverlay below (shared with the mobile nav drawers).
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setOpen((v) => !v);
      }
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, []);

  useDismissableOverlay(open, () => setOpen(false), panelRef);

  useEffect(() => {
    if (open) setTimeout(() => inputRef.current?.focus(), 30);
  }, [open]);

  const runSearch = useCallback(async (q: string) => {
    if (!q.trim()) {
      setResults([]);
      return;
    }
    const pagefind = await loadPagefind();
    if (!pagefind) {
      setUnavailable(true);
      return;
    }
    const search = await pagefind.search(q);
    const resolved = await Promise.all(
      search.results.slice(0, 8).map(async (r) => {
        const data = await r.data();
        return { id: r.id, url: data.url, title: data.meta?.title ?? data.url, excerpt: data.excerpt };
      }),
    );
    setResults(resolved);
    setActiveIdx(0);
  }, []);

  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => runSearch(query), 180);
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [query, runSearch]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setActiveIdx((i) => Math.min(i + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setActiveIdx((i) => Math.max(i - 1, 0));
    } else if (e.key === "Enter" && results[activeIdx]) {
      window.location.href = results[activeIdx].url;
    }
  };

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="flex items-center gap-2 border-2 border-[var(--hairline)] px-3 py-1.5 text-xs text-[var(--fg-muted)] transition-colors hover:border-[var(--edge)] hover:text-[var(--fg)]"
        aria-label="Search documentation"
      >
        <Search size={13} />
        <span className="hidden sm:inline">Search docs</span>
        <kbd className="hidden rounded-none border border-[var(--hairline)] px-1 font-mono text-[10px] sm:inline">⌘K</kbd>
      </button>

      {open && (
        <div className="fixed inset-0 z-[100] flex items-start justify-center bg-black/60 p-4 pt-[12vh]" onClick={() => setOpen(false)}>
          <div
            ref={panelRef}
            role="dialog"
            aria-modal="true"
            aria-label="Search documentation"
            className="edge-block w-full max-w-lg bg-[var(--bg)]"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center gap-2 border-b-2 border-[var(--edge)] px-4 py-3">
              <Search size={15} className="text-[var(--fg-muted)]" />
              <input
                ref={inputRef}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Search components, docs, headings…"
                role="combobox"
                aria-expanded={results.length > 0}
                aria-controls={listboxId}
                aria-activedescendant={results[activeIdx] ? `${listboxId}-${results[activeIdx].id}` : undefined}
                aria-autocomplete="list"
                className="flex-1 bg-transparent text-sm outline-none placeholder:text-[var(--fg-muted)]"
              />
              <button onClick={() => setOpen(false)} aria-label="Close search" className="text-[var(--fg-muted)] hover:text-[var(--fg)]">
                <X size={16} />
              </button>
            </div>

            <div className="max-h-[50vh] overflow-y-auto">
              {unavailable && (
                <p className="p-4 text-sm text-[var(--fg-muted)]">
                  Search index not found. Run <code>npm run build</code> to generate it (it is built from the static export).
                </p>
              )}
              {!unavailable && query.trim() && results.length === 0 && (
                <p role="status" className="p-4 text-sm text-[var(--fg-muted)]">
                  No results for &ldquo;{query}&rdquo;.
                </p>
              )}
              <ul id={listboxId} role="listbox" aria-label="Search results">
                {results.map((r, i) => (
                  <li key={r.id} role="presentation">
                    <a
                      id={`${listboxId}-${r.id}`}
                      href={r.url}
                      role="option"
                      aria-selected={i === activeIdx}
                      className={`block border-b border-[var(--hairline)] px-4 py-3 ${i === activeIdx ? "bg-[var(--surface)]" : ""}`}
                      onMouseEnter={() => setActiveIdx(i)}
                    >
                      <p className="font-display text-sm font-semibold">{r.title}</p>
                      <p
                        className="mt-1 text-xs text-[var(--fg-muted)]"
                        dangerouslySetInnerHTML={{ __html: r.excerpt }}
                      />
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
